---
title: <center>About
author: 
date: 
output: html_document
---

----

## How healthy are our oceans?

Determining ocean health requires an approach that integrates social, economic, and environmental information. The Ocean Health Index (OHI) does this by measuring progress towards widely held goals that represent key benefits and services provided by marine ecosystems. By analyzing these goals together we obtain a comprehensive picture of the state of the ecosystem. 

<br>

## Assessing Ocean Health in the Main Hawaiian Islands
 
We are building a scientifically robust index of ocean health for Hawaii that is supported by local stakeholders and integrated into ongoing policy initiatives to support sustainable ocean management. We are working within the OHI framework to facilitate repeatable assessments of the index goals overtime allowing for progress toward a common vision for a healthy ocean and sustainable ocean management.  

The process of developing and adapting the OHI for West Hawaii is extremely important for creating a culturally, socially, and ecologically appropriate tool for measuring ocean health in West Hawaii. The OHI is being adapted to meet the needs of West Hawaii and Hawaii with the support of local experts, stakeholder surveys, workshops and community meetings and integration with ongoing initiatives. 

<br> 

This website will serve as a communication platform as we work so that we can share the process as well as final results. <!--- Our code is available [here](https://github.com/OHI-Science/mhi). --->

<br> 

## Scale of Assessment

The Hawaii OHI assessment will use the scientifically robust framework of the Ocean Health Index at the scale of the Hawaiian archipelago. We will focus our development of the Hawaii Ocean Health Index at two scales:

1)	The West Hawaii region
2)	Statewide, for coastal waters


The Hawaii Statewide assessment which will focus on the Main Hawaiian Islands and will be at the island or island group scale. Regions will be Hawaii, Maui Nui, Oahu, and Kauai and Niihau. This scale is used to designate districts of Hawaii, which are used in policy and management for the State of Hawaii. 
To produce the spatial boundaries of these reporting units we use the Hawaii USA Exclusive Economic Zones (EEZ). A nearshore spatial scale is computed as the offshore 3nm boundary for Hawaii islands to be used in some goals. The OHI focus is on the entire EEZ, however, some goals are assessed on the nearshore (3 nm scale). 


## The Ocean Health Index project

The Ocean Health Index is a way to combine social, economic, and environmental data to measure progress towards a suite of benefits people expect healthy oceans to provide – including seafood, protection from storms, and employment. Every year since 2012, the Ocean Health Index team has tracked change in global ocean health for 220 coastal nations and territories. The team has also helped foster a growing network of independent groups around the world that are using our science to measure how healthy their own oceans are.  
<br>

Learn more and explore ongoing assessments at [ohi-science.org](http://ohi-science.org). Additionally, read our publications about [best practices for assessing ocean health](https://peerj.com/articles/1503/) and [how OHI assessments are transparent and repeatable](https://www.nature.com/articles/s41559-017-0160). A full list of publications is available [here](http://ohi-science.org/publications).
