### Goal Description
Oceans jobs and revenue directly provide 18% to the economy of Hawaiʻi. However there are many indirect economy benefits and markets. One could argue that the entire economy of Hawaii is based on the ocean. The attraction of visitors and tourism relies in part on a healthy ocean. In fact tourism and recreation is 90.5% of Hawaiʻi's ocean economy.

Economies captures the economic value associated with marine industries using revenue from marine sectors. It is composed of a single component, revenue.

### Model 

The Economies model assesses revenue from these marine sectors: Marine Construction, Living Resources, Ship and Boat Building, Tourism and Recreation, and Marine Transportation.

Revenue is adjusted by sector- and development status-specific multipliers derived from the literature to account not only for direct revenue, but also indirect and induced economic effects, since activity in the direct industry stimulates additional jobs and revenue in related industries.

### Reference points 

Because there is no absolute reference point for revenue (i.e., a target number of revenue would be completely arbitrary), its reference point is calculated as a relative value on a moving baseline: the value in the current year (or most recent year) relative to the value in a recent moving reference period, defined as 5 years prior to the current year. This reflects an implicit goal of maintaining coastal livelihoods and economies on short time scales, allowing for decadal or generational shifts in what people want and expect for coastal livelihoods and economy.

