### Goal Description

The Fisheries sub-goal describes the amount harvested and sustainability of Hawaiʻi's fisheries. The model generally compares landings with Maximum Sustainable Yield. A score of 100 means that the region is harvesting seafood in an sustainable manner. However, it is important to note that this assessment is based on relatively few formal stock assessments and many of the fish species that are included in this assessment lack stock assessments. To include these important fishery species, we made the assumption that the unassessed species within each fshery (pelagic, bottomfish, nearshore/reef, coastal pelagics) are fairing similarly to the assessed fish species.  

### Model 

The model assess the amount of wild-caught seafood that can be sustainably harvested, with sustainability based on foramal stock assessments. Each fish species is assessed separately based on sustainablility ratios (Biomass at maximum sustainable yeild: B/Bmsy; Spawning biomass at maximum sustainable yield: SB/SBmsy; and Spawning Potential Ratio: SPR) and weighted by its relative contribution to overall catch. The goal status score for each region in each year was calculated as average scores from each fishery calculated as the geometric mean of the all stock status scores for each fishery (pelagic: tuna, swordfish, mahimahi, etc.; bottomfish: deep seven species mainly groupers and snappers; coastal pelagics: jacks, akule, opelu, etc.; nearshore: surgeonfish, parrotfish, etc.)

### Reference points
Sustainability refernce points typically used in formal stock assessments vary by the fishery type in Hawaiʻi.
Pelagic fish sustainability reference point is SB/SBmsy set to 1.0.
Bottomfish species sustainability reference point is B/BMSY set to 1.0.
Reef fish sustainability reference point is the spawning potential ratio (SPR) set to 0.30.




