### Goal Description

Sense of Place goal tries to capture the aspects of the coastal and marine system that people value as part of their cultural identity through the relationship between people and ʻāina and relationships among people with regards to the past, present and future.This definition includes people living near the ocean and those who live far from it but still derive a sense of identity or value from knowing particular places or species exist. The sub-goal of Lasting Special Places measures the protection of marine and coastal areas and sacred and historical sites.

### Model  

The model measures the percentage of coastal marine protected area and protected coastline in each country, against a reference percentage. We focus on coastal waters (within 3 nautical miles of shore) and coastlines withing a  1 km-wide strip of land. The score for Lasting Special Places was assessed as the ratio of the total area protected to the total area.  


### Reference points 

The target reference level is 30% of coastal waters and nearshore coastal areas protected.  

