### Goal Description


Measures the sustainable production potential of seafood from fishponds, known locally as loko ʻia, and current production of seafood weighted by a sustainability score.

The value of aquaculture products ($39,970,000 in 2011 USD) natural products and seafood is ranked 4th in the state following seed crops, flowers and nursery products, and cattle (USDA Annual Statistics Bulletin 2011). However, revenue from mariculture is incorporated into Livelihoods and Economies goal.

### Model
The scores is an average of the state reported seafood produciton (mariculture) and fishpond potential.

The species that are reported on the State Department of Land and Natural Resources Division of Aquatic Resources that are produced locally for seafood consumption include: abalone (Haliotus sp), oysters (Crassostrea gigas and Crassostrea sikamea), clams (Venerupis philippinarum), kahala (Seriola dumerili), Pacific white shrimp (Penaeus vannamei), and limu (Gracilaria sp.). Moi (Pacific Threadfin) is not on the State of Hawaii Department of Agriculture list but it is produced locally for out planting in fishponds.  

The sustainability of the species produced was assessed as the average of the feed sustainability score (0 protein based, 1 plant based; 0 imported feed, 1 local feed) and the biosecurity risk scored as species status (1 native, 0.75 introduced, or 0 invasive) and the pathogen and virus susceptibility (0 highly susceptible, 0.5 susceptible but preventative measures in place (biosecurity practices such as sterilization and wastewater treatment practices). 

The production (lbs of seafood) is reported at the state level to prevent disclosure of sensitive information. To get county level estimates of production the lbs of finfish and shellfish produced at the state level were multiplied by the estimated number of finfish and shellfish operators by county. The number of operators are reported to USDA via census every 5 years (2002, 2007, 2012) (https://www.nass.usda.gov/Statistics_by_State/Hawaii/ ). To fill in annual data gaps linear regression models were used. 



### Reference points 

The mariculture score is calculated as the ratio of the lbs produced by county to the maximum lbs produced across regions.The fishpond score is the ratio of fishponds that are operation or being restored to 30% of the historic number. 
A region score will reach 100 when the region produces the maximum seafood produciton for the state and has a mimimum of 30% of the traditional fishponds restored or in the process of being restored.

