### Goal Description

People value biodiversity in particular for its existence value. The risk of species extinction generates great emotional and moral concern for many people. As such, the Biodiversity goal assesses the conservation status of species based on assessments of fish, marine mammals, turtles and birds, and coastal plants. 


### Model

Hawaiʻi has a high rate of endangered species. The latest assessment lists 501 Endangered species (77 animal) (Environmental Conservation Online System 02/13/2015). The Endangered Species Act (ESA) was established in 1973 provides for the conservation of species that are endangered or threatened (likely to become endangered in the near future without protection) throughout all or a significant portion of their range, and the conservation of the ecosystems on which they depend. To assess species status, we combined information on local reef fish species status indicators (NOAA report card/ HMARC), and ESA status of marine mammals, turtles, and birds, and coastal plants. We incorporated reef fish indicators even though many of Hawaiʻi’s reef fish are not considered threatened or endangered. Local indicators of reef fish populations and status are important for understanding the health of coral reefs and biodiversity and therefore were included through a reef fish indicator.

The reef fish indicator measures the average of 3 components: Reef Fish Biomass, Reef Fish Sustainability, and Reef Fish Predators (NOAA Coral Reef Conservation Program and University of Maryland Center for Environmental Science). Reef Fish Biomass measures the mean biomass of all reef fishes other than sharks and jacks derived from underwater visual surveys of <30m hard bottom habitats. Survey biomass per location is compared against a meaningful local baseline (to account for inherent environmental and habitat differences among locations). High scores therefore represent populations that are close to their natural carrying capacity. Reef Fish Sustainability represents an index of mean size for targeted reef fish species relative to their size at first maturity. High scores therefore represent assemblages where there are still many of large individuals of targets species, those large fishes being particularly important components of the breeding stock. The Reef Fish Predators indicator is made up of 2 components: 'reef sharks' and 'other reef piscivores' with data taken respectively from towed-diver and point-count surveys by divers. High scores represent locations where upper trophic level fishes are still a conspicuous and ecologically important component of the reef ecosystem.



### Reference points 

All marine mammals, turtles, and coastal plants are not threatended or endangered.
Reef fish biomass is equal to the local baseline for fish biomass (natural carrying capacity).
Reef fish harvest is sustainable with large, reproductively mature fish represented in the local populations.
Reef fish predators (sharks and piscivores) are present and close to baseline conditions (abundance and biomass before human impacts).

