---
output: html_document
---

```{r set up, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
library(tidyverse)
library(stringr)

## information from layers.csv
key <- "mhi"
dir_scenario_gh <- "https://raw.githubusercontent.com/OHI-Science/mhi/master/region2017"
layers_csv  <- readr::read_csv(file.path(dir_scenario_gh, 'layers.csv'))
layers_web <- sprintf('http://ohi-science.org/%s/layers.html', key)
```

```{r}

## excel filepath relative to region2017/conf/web
dir_excel <- "../../../prep"
dir_layers <- "https://github.com/OHI-Science/mhi/blob/master/region2017/layers/"

## read in excel sheet
layers_excel <- readxl::read_excel(path = file.path(dir_excel, "OHI_state assessment_framework.xlsx"), sheet = "Data_Layers") 
names(layers_excel)

## rename a few columns
layers_info <- layers_excel %>%
  dplyr::select(header_layer = `Data Layer`, 
                layer_name    = Name,
                description   = `Brief Description`, 
                reference     = Reference) %>%
  arrange(layer_name)

```


```{r}
## Loop through all columns and format for web
## Notes: uses regular expessions, check out https://www.rstudio.com/resources/cheatsheets/. 
  ## "^" is the beginning of a line
  ## "$" is the end of a line

st <- layers_info %>%
  ## header
  # mutate(header = str_to_title(layer_english)) %>%
  # mutate(header = str_replace(header, "^", "## ")) %>%
  # mutate(header = str_replace(header, "$", "\n\n")) %>%
  # 
  
  
  ## description
  # mutate(description = str_trim(description, side = "both")) %>%
  # mutate(description = str_replace(description, "$", "\n\n")) %>%
  
  ## reference
  mutate(header_ref = "### Reference\n\n") %>%
  # mutate(reference  = str_replace(reference, "$", "\n\n")) %>% 
  mutate(url_ref    = "this_will_be_a_link") %>%
  
  ## all together now
   mutate(info = paste0("## ", header_layer, "\n\n", 
                        sprintf("[%s](%s)\n\n", layer_name, dir_layers), 
                        description, "\n\n",
                        header_ref, 
                        sprintf("[%s](%s)", reference, url_ref)))

## save rmd
st1 <- st[1,]

write_file(st1$info, "st.Rmd")


## and paste it so it renders like Markdown
cat(paste(st$info, collapse="\n\n"))
         

#mutate(header = str_pad(layer_english, width = 1, side = "left", pad = "## "))


```

## Food Provision: Fisheries

```{r, child='goals/FIS.Rmd', results='asis', echo=FALSE}
```

### Data used in model

**Status & trend**

```{r, echo=FALSE, warning=FALSE, error=FALSE, results="asis"}
st <- layers_csv %>%
  filter(targets=="FIS") %>%
  mutate(web_name = gsub(" ", "_", name)) %>%
  mutate(web_name = tolower(web_name)) %>%
  mutate(web_name = gsub("/", "", web_name)) %>%
  mutate(info = sprintf("[%s](%s#%s) (%s): %s", name, layers_web, web_name, layer, description))

cat(paste(st$info, collapse="\n\n"))
```

---- 
